# Generated by Django 4.1.1 on 2022-09-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('uuid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('heigth', models.FloatField(verbose_name='Peso')),
                ('price', models.FloatField(verbose_name='Precio')),
                ('image', models.ImageField(upload_to='static', verbose_name='Foto')),
            ],
        ),
    ]
