# Generated by Django 4.1.1 on 2022-09-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('uuid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('price', models.FloatField(verbose_name='Precio')),
                ('image', models.ImageField(upload_to='static', verbose_name='Foto')),
                ('category', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('heigth', models.FloatField(verbose_name='Peso')),
            ],
            options={
                'verbose_name': 'Juego',
                'verbose_name_plural': 'Juegos',
            },
        ),
        migrations.CreateModel(
            name='MesureUnit',
            fields=[
                ('uuid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medidas',
            },
        ),
        migrations.CreateModel(
            name='Plataform',
            fields=[
                ('uuid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Plataforma',
                'verbose_name_plural': 'Plataformas',
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='game',
            name='mesure_unit',
            field=models.ForeignKey(blank=True, on_delete=models.SET(''), to='Product.mesureunit'),
        ),
        migrations.AddField(
            model_name='game',
            name='plataform',
            field=models.ForeignKey(blank=True, on_delete=models.SET(''), to='Product.plataform'),
        ),
    ]
