# Generated by Django 4.1.1 on 2022-09-11 08:06

import Product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_mesureunit_active_plataform_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, default='http://127.0.0.1:8000/media/default.jpg', upload_to=Product.models.image_upload, verbose_name='Foto'),
        ),
    ]
