# Generated by Django 4.1.1 on 2022-09-11 08:07

import Product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_alter_game_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=Product.models.image_upload, verbose_name='Foto'),
        ),
    ]
