# Generated by Django 4.1.1 on 2022-09-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_alter_game_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='mesure_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(''), to='Product.mesureunit'),
        ),
        migrations.AlterField(
            model_name='game',
            name='plataform',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(''), to='Product.plataform'),
        ),
    ]
