# Generated by Django 4.1.1 on 2022-09-13 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_alter_game_mesure_unit_alter_game_plataform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='heigth',
            new_name='size',
        ),
    ]
