# Generated by Django 4.1.1 on 2022-09-13 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_rename_heigth_game_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='mesure_unit',
            new_name='um',
        ),
    ]
